config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do
      post :vote
    end
  end
  root "candidates#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :vote_logs, dependent: :destroy
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  #layout false
  before_action :find_candidate, only: [:edit, :update, :destroy, :vote]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @candidates = Candidate.all

  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      # 成功
      redirect_to candidates_path, notice: '新增候選人成功!'
    else
      # 失敗
      render :new
      #重新顯示已經填過資料那頁，而不是導一個新的頁面給使用者
      #
      #
      #

    end
  end


  def edit
  end

  def update
    if @candidate.update(candidate_params)
      # 成功
      redirect_to candidates_path, notice: "資料更新成功!"
    else
      # 失敗
      render :edit
    end
  end

  def vote
    @candidate.vote_logs.create(ip_address: request.remote_ip) if @candidate
    redirect_to candidates_path, notice: "完成投票!"
  end
  def method_name

  end

  def destroy
    @candidate.destroy if @candidate
    redirect_to candidates_path, notice: "候選人資料已刪除!"
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :age, :party, :politics)
  end

  def find_candidate
    begin
      @candidate = Candidate.find(params[:id])
    rescue
      redirect_to candidates_path, notice: "查無此候選人"
    end
  end
  def record_not_found
    render plain: "查無資料", status: 404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_gender(gender)
    if gender == 1
      "男"
    elsif gender == 0
      "女"
    else
      "男/女"
    end
  end

  def icon_link_to(label, path, icon)
    link_to path do
      content_tag :span, class: "glyphicon glyphicon-#{icon}" do
        label
      end
    end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_banner.html.erb
<div class="advertisement">
  <div>廣告.html.erb</div>
  <div> <%= content %> </div>
</div>

app/views/candidates/_candidate.html.erb
<tr>
  <td><%= link_to "投給這位",vote_candidate_path(candidate), method: "post", data: { confirm: "確定投給這個人?" }, class:"btn btn-danger btn-xl"  %></td>
  <td><%= candidate.name %>(年齡：<%= candidate.age %> 歲)</td>
  <td><%= candidate.party %></td>
  <td><%= candidate.politics %></td>
  <td><%= candidate.vote_logs.size %></td>
  <td>
    <%= link_to "編輯", edit_candidate_path(candidate) %>
    <%= link_to "刪除", candidate_path(candidate), method: "delete", data: {confirm: "確認刪除" } %>
  </td>
</tr>

app/views/candidates/_form.html.erb
<%= simple_form_for(candidate) do |f| %>
    <%= f.input :name, label: "姓名" %>
    <%= f.input :age, label: "年齡" %>
    <%= f.input :party, label: "政黨" %>
    <%= f.input :politics, label: "政見" %>
    <%= f.submit %>

<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

  <%= render "form", candidate: @candidate %>

  <br />
<%= link_to '回候選人列表', candidates_path %>

app/views/candidates/index.html.erb
<% provide :my_title, "你好，我是 Title" %>

<h1>候選人列表</h1>
<%= icon_link_to "新增候選人", new_candidate_path, "plus" %>

<table class="table">
  <thead>
    <tr>
      <td>候選人姓名</td>
      <td>政黨</td>
      <td>政見</td>
      <td>得票數</td>
      <td>得票數</td>
      <td>處理</td>
      <td><%= user_gender(-1) %></td>
    </tr>
  </thead>
  <tbody>
    <%= render @candidates %>
    <%= render "banner", content: "我是廣告的內容2" %>
  </tbody>

</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstVoting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>網站管理系統</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>我是後台</h1>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>